### ISSUE TITLE
alertify is undefined

### ISSUE THREAD

**Issue by JogoShugh** [bahattincinic/meteor-alertify#1]
I was glad to see this package! Unfortunately, I get this:

window.alertify
undefined

**Comment by bahattincinic** [comment]
Which version ?

**Try 1.0.2.1 version:**
![screen shot 2015-01-05 at 10 40 47 pm](https://cloud.githubusercontent.com/assets/1684999/5619600/200144f2-952c-11e4-9fcd-a47766cd28b2.png)

**Comment by JogoShugh** [comment]
OK thanks, will do
